# Eureka
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${random.int}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    
# Endpoints
endpoints:
  restart:
    enabled: true
       
# Server
server:
  port: 8090
 
spring: 
  jackson:
    time-zone:
      "UTC"
  jpa:
    show-sql: false
    hibernate:
      jdbc:
        time_zone: "UTC" 
  data:
    mongodb:
      uri: mongodb://rodrigo:123456@localhost/projeto


